apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: OnFailure              
  containers:
  - name: hello
    image: "alpine:latest"
    command: ["/bin/echo","Hello","world"]